name: Manage Kaggle Notebooks

on:
  schedule:
    - cron: '0 0,9,18 * * *'  # 每天00:00、09:00和18:00运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Prepare Notebook With Timestamp
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          mkdir -p ${NOTEBOOK_DIR}
          cp script/main.py ${NOTEBOOK_DIR}/main.py
          cp script/kernel-metadata.json ${NOTEBOOK_DIR}/kernel-metadata.json

      - name: Push and Run Notebook
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          kaggle kernels push -p ${NOTEBOOK_DIR}
          echo "Notebook submitted and running."

      - name: Clean Up
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          rm -rf notebook_${TIMESTAMP}
          echo "Temporary notebook folder deleted."
