name: Manage Kaggle Notebooks

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 21/9 * * *'  # 定时任务，每12小时触发一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许推送到仓库

jobs:
  run-notebooks:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境上运行
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout code  # 检出当前的代码仓库
        uses: actions/checkout@v3

      - name: Install dependencies  # 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Setup Kaggle API credentials  # 设置 Kaggle API 凭证
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Determine Notebook Title  # 确定 Notebook 标题
        id: determine-title
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_TITLE="notebook_${TIMESTAMP}"
          
          echo "NOTEBOOK_TITLE=${NOTEBOOK_TITLE}" >> $GITHUB_ENV
      
      - name: Prepare and Push Notebook  # 准备并推送 Notebook
        run: |
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          
          echo "Creating directory: ${NOTEBOOK_DIR}"
          mkdir -p ${NOTEBOOK_DIR}
          
          echo "Copying files into ${NOTEBOOK_DIR}"
          cp -v script/main.py ${NOTEBOOK_DIR}/main.py
          cp -v script/kernel-metadata.json ${NOTEBOOK_DIR}/kernel-metadata.json
          
          echo "Updating kernel-metadata.json with title: ${NOTEBOOK_TITLE}"
          sed -i "s/\"title\": \".*\"/\"title\": \"${NOTEBOOK_TITLE}\"/" ${NOTEBOOK_DIR}/kernel-metadata.json
          
          kaggle kernels push -p ${NOTEBOOK_DIR} || { echo "Failed to push notebook to Kaggle"; exit 1; }
