name: Manage Kaggle Notebooks

on:
  schedule:
    - cron: '0 0,9,18 * * *'
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Install Kaggle CLI
        run: |
          pip install kaggle

      - name: Prepare Notebook With Timestamp
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          NOTEBOOK_TITLE="Notebook_${TIMESTAMP}"
          
          echo "Creating directory: ${NOTEBOOK_DIR}"
          mkdir -p ${NOTEBOOK_DIR}
          
          echo "Copying files into ${NOTEBOOK_DIR}"
          cp -v script/main.py ${NOTEBOOK_DIR}/main.py
          cp -v script/kernel-metadata.json ${NOTEBOOK_DIR}/kernel-metadata.json
          
          echo "Updating kernel-metadata.json"
          sed -i "s/\"title\": \".*\"/\"title\": \"${NOTEBOOK_TITLE}\"/" ${NOTEBOOK_DIR}/kernel-metadata.json
          
          echo "Notebook Directory: ${NOTEBOOK_DIR}"
          ls -l ${NOTEBOOK_DIR}

      - name: Submit Notebook to Kaggle
        run: |
          echo "Submitting notebook with title: ${NOTEBOOK_TITLE}"
          kaggle kernels push -p ${NOTEBOOK_DIR} || { echo "Failed to push notebook to Kaggle"; exit 1; }
