name: Conditional Kaggle Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点执行

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dayOfWeek: [1, 2, 3, 4, 5, 6, 7]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get day of the week
        id: get-day
        run: echo "dayOfWeek=$(date +'%u')" >> $GITHUB_ENV  # 1 (Monday) to 7 (Sunday)

      - name: Set up Kaggle CLI
        if: ${{ matrix.dayOfWeek == env.dayOfWeek }}
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets['KAGGLE_USERNAME_ACCOUNT' + matrix.dayOfWeek] }}\",\"key\":\"${{ secrets['KAGGLE_KEY_ACCOUNT' + matrix.dayOfWeek] }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          kaggle kernels push -p .github/workflows
