name: Push Python Script to Kaggle and Stop Script

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点执行
    - cron: '59 23 * * *' # 每天23:59执行

jobs:
  push-and-stop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kaggle CLI
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Push Python script to Kaggle
        if: ${{ github.event.schedule.cron == '0 0 * * *' }}  # 仅在每天0点时推送
        run: |
          kaggle kernels push -p .github/workflows

      - name: Stop Python script
        if: ${{ github.event.schedule.cron == '59 23 * * *' }}  # 仅在每天23:59时执行停止操作
        run: |
          echo "Stopping Python script at 23:59"
          pkill -f main.py  # 使用 pkill 通过脚本名停止 Python 脚本
