name: Manage Kaggle Notebook  # GitHub Actions 的名称

on:
  schedule:
    - cron: '0 0,9,18 * * *'  # 定时任务，每天的00:00、09:00和18:00触发一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-notebooks:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境上运行
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout code  # 检出当前的代码仓库
        uses: actions/checkout@v2

      - name: Setup Kaggle API credentials  # 设置 Kaggle API 凭证
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Install Kaggle CLI  # 安装 Kaggle CLI 工具
        run: |
          pip install kaggle

      - name: Prepare Notebook With Timestamp  # 准备带有时间戳的 Notebook 文件夹
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          echo "Creating notebook directory: ${NOTEBOOK_DIR}"
          mkdir -p ${NOTEBOOK_DIR}
          cp script/main.py ${NOTEBOOK_DIR}/main.py
          cp script/kernel-metadata.json ${NOTEBOOK_DIR}/kernel-metadata.json

      - name: Verify Notebook Directory  # 验证 Notebook 文件夹
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          if [ -d "${NOTEBOOK_DIR}" ]; then
            echo "Notebook directory ${NOTEBOOK_DIR} exists."
            ls -l ${NOTEBOOK_DIR}
          else
            echo "Notebook directory ${NOTEBOOK_DIR} does not exist."
            exit 1
          fi

      - name: Submit and Run Notebook  # 提交并运行 Notebook
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          NOTEBOOK_TITLE="Notebook_${TIMESTAMP}"
          echo "Submitting notebook with title: ${NOTEBOOK_TITLE}"
          
          # Verify the directory before submitting
          if [ -d "${NOTEBOOK_DIR}" ]; then
            echo "Directory ${NOTEBOOK_DIR} exists, proceeding with submission."
            kaggle kernels push -p ${NOTEBOOK_DIR}
            kaggle kernels create -p ${NOTEBOOK_DIR} --title "${NOTEBOOK_TITLE}"
            echo "Notebook ${NOTEBOOK_TITLE} submitted."
          else
            echo "Directory ${NOTEBOOK_DIR} does not exist. Cannot submit notebook."
            exit 1
          fi

      - name: Clean Up  # 清理临时文件夹
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NOTEBOOK_DIR="notebook_${TIMESTAMP}"
          rm -rf ${NOTEBOOK_DIR}
          echo "Temporary notebook folder deleted."
