name: Push Python Script to Kaggle and Stop Script

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点执行
    - cron: '59 23 * * *' # 每天23:59执行
  workflow_dispatch:  # 允许手动触发

jobs:
  push-and-stop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get day of the week
        id: get-day
        run: echo "dayOfWeek=$(date +'%u')" >> $GITHUB_ENV

      - name: Set up Kaggle CLI
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          # 根据 dayOfWeek 选择对应的账户
          if [ "${{ env.dayOfWeek }}" == "1" ]; then
            echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME_ACCOUNT1 }}\",\"key\":\"${{ secrets.KAGGLE_KEY_ACCOUNT1 }}\"}" > ~/.kaggle/kaggle.json
          elif [ "${{ env.dayOfWeek }}" == "2" ]; then
            echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME_ACCOUNT2 }}\",\"key\":\"${{ secrets.KAGGLE_KEY_ACCOUNT2 }}\"}" > ~/.kaggle/kaggle.json
          elif [ "${{ env.dayOfWeek }}" == "3" ]; then
            echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME_ACCOUNT3 }}\",\"key\":\"${{ secrets.KAGGLE_KEY_ACCOUNT3 }}\"}" > ~/.kaggle/kaggle.json
          elif [ "${{ env.dayOfWeek }}" == "4" ]; then
            echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME_ACCOUNT4 }}\",\"key\":\"${{ secrets.KAGGLE_KEY_ACCOUNT4 }}\"}" > ~/.kaggle/kaggle.json
          elif [ "${{ env.dayOfWeek }}" == "5" ]; then
            echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME_ACCOUNT5 }}\",\"key\":\"${{ secrets.KAGGLE_KEY_ACCOUNT5 }}\"}" > ~/.kaggle/kaggle.json
          elif [ "${{ env.dayOfWeek }}" == "6" ]; then
            echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME_ACCOUNT6 }}\",\"key\":\"${{ secrets.KAGGLE_KEY_ACCOUNT6 }}\"}" > ~/.kaggle/kaggle.json
          elif [ "${{ env.dayOfWeek }}" == "7" ]; then
            echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME_ACCOUNT7 }}\",\"key\":\"${{ secrets.KAGGLE_KEY_ACCOUNT7 }}\"}" > ~/.kaggle/kaggle.json
          fi
          chmod 600 ~/.kaggle/kaggle.json

      - name: Push Python script to Kaggle
        if: ${{ (github.event_name == 'schedule' && github.event.schedule.cron == '0 0 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'push') }}
        run: |
          kaggle kernels push -p .github/workflows

      - name: Stop Python script
        if: ${{ (github.event_name == 'schedule' && github.event.schedule.cron == '59 23 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'stop') }}
        run: |
          echo "Stopping Python script"
          pkill -f main.py
