name: Push Python Script to Kaggle and Stop Script

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点执行
    - cron: '59 23 * * *' # 每天23:59执行
  workflow_dispatch:  # 允许手动触发

jobs:
  push-and-stop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get day of the week
        id: get-day
        run: echo "dayOfWeek=$(date +'%u')" >> $GITHUB_ENV

      - name: Set up Kaggle CLI
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets['KAGGLE_USERNAME_ACCOUNT' + env.dayOfWeek] }}\",\"key\":\"${{ secrets['KAGGLE_KEY_ACCOUNT' + env.dayOfWeek] }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Push Python script to Kaggle
        if: ${{ (github.event_name == 'schedule' && github.event.schedule.cron == '0 0 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'push') }}
        run: |
          kaggle kernels push -p .github/workflows

      - name: Stop Python script
        if: ${{ (github.event_name == 'schedule' && github.event.schedule.cron == '59 23 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'stop') }}
        run: |
          echo "Stopping Python script"
          pkill -f main.py
